name       : openldap
version    : 2.4.46
release    : 6
source     :
    - https://www.openldap.org/software/download/OpenLDAP/openldap-release/openldap-2.4.46.tgz : 9a90dcb86b99ae790ccab93b7585a31fbcbeec8c94bf0f7ab0ca0a87ea0c4b2d
license    : OLDAP-2.8
component  : security
summary    : An open source implementation of the Lightweight Directory Access Protocol.
description: |
    An open source implementation of the Lightweight Directory Access Protocol.
emul32     : yes
builddeps  :
    - pkgconfig32(com_err)
    - pkgconfig32(krb5)
    - pkgconfig32(libsasl2)
    - pkgconfig32(openssl)
    - pkgconfig32(sqlite3)
    - pkgconfig32(uuid)
    - glibc-32bit-devel
    - groff
    - libgcc-32bit
    - libpth-32bit-devel
    - unixodbc-32bit-devel
setup      : |
    %configure --disable-static \
        --disable-bdb \
        --disable-hdb \
        --disable-ndb \
        --disable-perl \
        --enable-backends \
        --enable-ipv6 \
        --enable-spassword \
        --with-cyrus-sasl \
        --with-threads \
        --with-tls=openssl
build      : |
    %make depend
    %make
install    : |
    %make_install
    rm -rf $installdir/var
