name       : openldap
version    : 2.4.44
release    : 4
source     :
    - ftp://ftp.openldap.org/pub/OpenLDAP/openldap-release/openldap-2.4.44.tgz : d7de6bf3c67009c95525dde3a0212cc110d0a70b92af2af8e3ee800e81b88400
license    : OpenLDAP Public License 2.8
component  : security
summary    : An open source implementation of the Lightweight Directory Access Protocol.
description: |
    An open source implementation of the Lightweight Directory Access Protocol.
emul32     : yes
builddeps  :
    - pkgconfig(com_err)
    - pkgconfig32(com_err)
    - pkgconfig(krb5)
    - pkgconfig32(krb5)
    - pkgconfig(libsasl2)
    - pkgconfig32(libsasl2)
    - pkgconfig(openssl)
    - pkgconfig32(openssl)
    - pkgconfig(uuid)
    - pkgconfig32(uuid)
    - pkgconfig(sqlite3)
    - pkgconfig32(sqlite3)
    - glibc-32bit-devel
    - libgcc-32bit
    - libpth-32bit-devel
    - unixodbc-32bit-devel
setup      : |
    %configure --disable-static \
        --disable-bdb \
        --disable-hdb \
        --disable-ndb \
        --disable-perl \
        --enable-backends \
        --enable-ipv6 \
        --enable-spassword \
        --with-cyrus-sasl \
        --with-threads \
        --with-tls=openssl
build      : |
    %make depend
    %make
install    : |
    %make_install
    rm -rf $installdir/var
